javascript sdk uses successor logic for swap tx
alonfalsing/zksync pull request #2
Opened 2022-07-08 07:23 UTC by derekzTu

2022-07-08 13:14 UTC, alonfalsing requested changes

2022-07-08 13:14 UTC, alonfalsing commented on sdk/zksync.js/src/wallet.ts
> +    async getSucc(nonce: Nonce = null): Promise<number> {
`Nonce` is either `number` or `'committed'`. `getSucc()` does not exhaust all the cases.

2022-07-08 13:14 UTC, alonfalsing commented on sdk/zksync.js/src/wallet.ts
> +        const nonce = order.nonce != null ? await this.getSucc(order.nonce) : await this.getSucc();
As the type annotation states, `order.nonce` should not be `null`. A non-strict equal is applied here, which is not a typical typescript style. Is that intentional and shall we follow the pattern?

2022-07-08 19:20 UTC, derekzTu commented on sdk/zksync.js/src/wallet.ts
> +    async getSucc(nonce: Nonce = null): Promise<number> {
So should I change the default param back to 'commited'?

2022-07-08 19:22 UTC, derekzTu commented on sdk/zksync.js/src/wallet.ts
> +        const nonce = order.nonce != null ? await this.getSucc(order.nonce) : await this.getSucc();
I thought that `order.nonce != null` is used because `nonce` is an optional param so will not always be defined.

2022-07-11 07:44 UTC, phanalpha commented on sdk/zksync.js/src/wallet.ts
> +    async getSucc(nonce: Nonce = null): Promise<number> {
Changing default to `committed` should work, but not necessary. The point is that we should cover all cases.

2022-07-11 07:49 UTC, phanalpha commented on sdk/zksync.js/src/wallet.ts
> +        const nonce = order.nonce != null ? await this.getSucc(order.nonce) : await this.getSucc();
In javascript, an optional parameter would get `undefined` if omitted. We would prefer not to use non-strict equality if possible. The question is why we do not use strict equality (`!==`) here.

2022-07-12 03:31 UTC, derekzTu commented on sdk/zksync.js/src/wallet.ts
> +    async getSucc(nonce: Nonce = null): Promise<number> {
Ah okay sorry I get what you're saying now, I will add the  `committed` case so there will be a case for `null`, `committed`, `number`.

2022-07-12 03:35 UTC, derekzTu commented on sdk/zksync.js/src/wallet.ts
> +        const nonce = order.nonce != null ? await this.getSucc(order.nonce) : await this.getSucc();
I cannot think of a reason to keep it non-strict. If non-strict is non-typical I will switch to `!==` for now

2022-07-15 05:53 UTC, alonfalsing commented on sdk/zksync.js/src/wallet.ts
> +    async getSucc(nonce: Nonce = null): Promise<number> {
```typescript
if (typeof nonce == 'number') {
    return nonce;
}

return (await this.provider.getState(this.address())).committed.succ;
```

2022-07-15 05:58 UTC, alonfalsing commented on sdk/zksync.js/src/wallet.ts
> +        const nonce = order.nonce !== null ? await this.getSucc(order.nonce) : await this.getSucc();
Simply changing to strict non-equality does not help. `order.nonce` is either `undefined` or `Nonce`, thus `order.nonce !== null` will be false here.

2022-07-15 06:20 UTC, derekzTu commented on sdk/zksync.js/src/wallet.ts
> +        const nonce = order.nonce !== null ? await this.getSucc(order.nonce) : await this.getSucc();
I see I was confused by what the original code had. Is there a reason why the old code had a non-equality to null?

2022-07-15 06:36 UTC, alonfalsing commented on sdk/zksync.js/src/wallet.ts
> +        const nonce = order.nonce !== null ? await this.getSucc(order.nonce) : await this.getSucc();
Javascript/typescript is different from other languages, which distinguish `null` and `undefined`. Non-strict equality and comparing to `null` may come with foreign taste. It does work, but there's little advantage to use it.

2022-07-15 06:47 UTC, merged